Project
darklight81/pwn-task pull request #1
Opened 2023-01-17 18:05 UTC by darklight81

Possible enhancements:

- UI
- More optimal use of typescript
- Error handling when a Web3 provider is not installed
- Implement logic of 'sendChange()' in AssetItem component differently, the code doesn't seem clean to me right now, but I was not sure how to refactor it to make more sense
- Get Rid of <Suspense> as it is experimental
- Assets reload on the different response from APIs

2023-01-17 23:40 UTC, microHoffman requested changes

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +const success = ref<string | null>(null);
using `ref(null)` works just the same as just `ref()`

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +const signerAddress: string = await signer.getAddress();
1) We are mixing here the declaration of variables (`tokensToWrap, error, success, options, options2`) with the actual async method calls, which makes the code more confusing than needed. Also the order of the statements seems a little bit random, e.g. defining `options2` and then calling `await signer.getAddress()`

2) It makes more sense to me to extract the logic for login to it's separate function

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +const moralisRes = await fetch(`https://deep-index.moralis.io/api/v2/${signerAddress}/erc20?chain=goerli`, options2)
here we are unnecesarily waiting first for `openseaRes` to complete before we start with fetching data from moralis... this is not necessary, using `Promise.all` to run both promises in parallel should be a way to go here

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +const moralisRes = await fetch(`https://deep-index.moralis.io/api/v2/${signerAddress}/erc20?chain=goerli`, options2)
also separating fetching of assets should be imho extracted into functions (one for moralis, one for opensea), ideally put them outside of the vue component file and just call them from the component

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +    </div>
minor thing, maybe using conditional class for styling of the message to be displayed might be worth

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +}
I like defining interface here, BUT:

1) IMHO we should not work in our app with the external `OpenseaAsset` and `MoralisAsset`... what makes sense to me is to create our own `Asset` class and in our codebase we will use just this class... only in opensea/moralis fetching functions (adapters), we would fetch the response and parse it into our `Asset` class. We could also add an `amount` to this `Asset`  class.

This way we could also avoid conditions like `v-if="asset.asset_contract"` which are really confusing, since all assets have asset contract and it's just using the implementation detail of how the opensea object of NFT looks like, which is kinda hacky.

Note: one slight modification to our `Asset` object could be to create also `ERC20Asset` and `NFTAsset` child classes, but for project of this size it's imho unnecessary.

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +jsonAssets.map((asset: MoralisAsset) => {assets.push(asset)})
alternative would to just call `assets.concat(jsonAssets)`

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +    const balance = await tokenContract.balanceOf(signerAddress);
why are we fetching `balance` here? we are getting the user balance of certain token directly in moralis response:)

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +    const amount = token.amount * 10 ** token.asset.decimals;
definitely, **never** use normal JS `Number` type for ethereum amounts

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +    await tokenContract.approve(TokenBundlerAddress, amount.toString());
one tweak here could be to add a check, if the user already gave an approval for the token, so he does not need to do it every time he wants to wrap this token

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +    await tokenContract.approve(TokenBundlerAddress, amount.toString());
same goes for checking approvals for nfts

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +    const amount = token.amount * 10 ** token.asset.decimals;
there are also utils functions in `ethers` like `formatUnits` and `parseUnits` that helps with decimals

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +  await Promise.all(tokensToWrap.map( token => handleToken(token, tokensToWrapMultiToken)))
+1 for `Promise.all`:)

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +  await tokenBundlerContract.create(tokensToWrapMultiToken, {gasLimit: 1000000}).then(() => {
have you tried removing the `gasLimit`? 

on the code consistency part: you mostly use `async`/`await`, but here you are also mixing the `then` style

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +function logChange({asset, amount, add}) {
`logChange`?

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +      window.location.reload();
why reload full page?

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +  display: flex;
+1:), also for some usecases grid can be quite handy + browser support is pretty nice already

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +  font-size: 16px;
also possible to use `rem` units, which we use mostly in our codebase:)

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +  <div v-if=asset.asset_contract class="asset">
1) hmm, i've never seen the `v-if` value without `"`, but seems like it's working:D

2) imho the condition is unclear of what it means, but i've wrote more about it in the `HelloWorld` file:)

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +    <img class="token__image" :src=asset.image_preview_url>
question: is the BEM class name style here intentional? we are using it in our codebase:)

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +  <!-- TEMPLATE FOR ERC20 -->
appreaciate the comment, but imho by making the condition clear, it would be readable already:)

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +    <form v-if="hasInput" @submit.prevent="sendChange">
no need to use `<form>`

2023-01-17 23:40 UTC, microHoffman commented on src/components/HelloWorld.vue
> +let assets : Array<OpenseaAsset | MoralisAsset> = jsonAssets.assets
this should be either `reactive` or `ref` + especially since we are using it in the template, we should declare this variable at the top of the `<script>` part to make clear what variables are temporary and what variables we use in template/in other places:)

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +const emit = defineEmits<{(e: 'customChange', asset: Record<string, unknown>): void}>()
I think the type here is incorrect, we know the type of `asset` right? I think it should be `OpenseaAsset | MoralisAsset`?

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +let hasInput = true
either make this `ref`, or even better probably is using `computed` here like `const hasInput = computed(() => props.asset.asset_contract.schema_name === "ERC1155"` (+ ERC20)...

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +  if (event.target.btn){
what is the purpose of this `if`?

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +    <button v-else class="button" @click="sendChange">Add token</button>
hmm im confused here:D

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +        const amount = event.target.amount.value
imho this is very non-vue style to do things like this... ideally we should just declare a `const amount = ref()` variable and pass it to `<input>` like this: `<input v-model="amount">`...

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +const emit = defineEmits<{(e: 'customChange', asset: Record<string, unknown>): void}>()
`customChange` is very general name of the emit

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +const sendChange = (event: unknown) => {
i think this whole function should be refactored, since it is really complicated, with lot of nested ifs, etc., which is probably also related to not using `v-model` (described below)

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +    event.target.innerText = "Remove token"
i think we should never change a text of element in vue like this... we can use either `computed` or `ref` variable

2023-01-17 23:40 UTC, microHoffman commented on src/components/AssetItem.vue
> +  background-color: #4CAF50; /* Green */
css variables could be your friend, although in the scope of this task it's not really necessary:)

2023-01-18 11:45 UTC, darklight81 commented on src/types/OpenseaAsset.ts
> +export interface OpenseaAsset {
I generated the interface through https://quicktype.io/typescript from the API responses. Is that ok?

2023-01-18 11:50 UTC, darklight81 commented on src/types/MoralisAsset.ts
> +    thumbnail?:     null;
You're right, it was auto-generated from the response, so it automatically assigned types by the only response I fed it.

2023-01-18 15:16 UTC, microHoffman commented on src/types/OpenseaAsset.ts
> +export interface OpenseaAsset {
That's cool, I was actually thinking about creating something similar, but I did not know it already exist:)

2023-01-18 15:17 UTC, microHoffman commented on src/types/MoralisAsset.ts
> +    thumbnail?:     null;
Is there an option to give multiple responses to that QuickType tool to prevent this?

2023-01-19 18:06 UTC, darklight81 commented on src/components/AssetItem.vue
> +    <img class="token__image" :src=asset.image_preview_url>
Not really, probably auto-completed by copilot...

2023-03-16 10:10 UTC, closed without merging